# Generated by Django 5.2.15 on 2026-07-03 06:01

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source_file', models.FileField(blank=True, upload_to='corpus/%Y/')),
                ('source_name', models.CharField(blank=True, help_text='Original filename or path the document came from.', max_length=500)),
                ('tier', models.PositiveSmallIntegerField(choices=[(1, 'Tier 1 — policies, handbooks, schedules (no student data)'), (2, 'Tier 2 — curriculum & lesson plans (not enabled)'), (3, 'Tier 3 — student records (not enabled)')], default=1)),
                ('last_updated', models.DateField(blank=True, help_text="When the document's content was last revised — shown with every citation.", null=True)),
                ('content_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingested_at', models.DateTimeField(blank=True, null=True)),
                ('allowed_roles', models.ManyToManyField(blank=True, help_text='Only these roles can ever retrieve this document. No roles = nobody.', related_name='documents', to='accounts.role')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='corpus.document')),
            ],
            options={
                'ordering': ['document', 'index'],
                'constraints': [models.UniqueConstraint(fields=('document', 'index'), name='unique_chunk_index_per_document')],
            },
        ),
    ]
