# Generated by Django 5.2.15 on 2026-07-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('tier', 1)), name='document_tier_1_only'),
        ),
    ]
