# Generated by Django 5.2.15 on 2026-07-03 07:52

from django.conf import settings
from django.db import migrations, models


def backfill_embedding_provenance(apps, schema_editor):
    """Stamp already-ingested documents with the current embedder identity, so an
    existing deployment's corpus stays searchable across this upgrade instead of
    going dark (retrieval excludes documents with unknown/mismatched provenance).
    We assume existing chunks were produced by the configured embedder — true
    unless the operator is also changing EMBEDDING_* in the same upgrade, in which
    case `manage.py check_embeddings --fix` re-ingests to confirm."""
    Document = apps.get_model("corpus", "Document")
    backend = settings.EMBEDDING_BACKEND
    model = settings.EMBEDDING_MODEL if backend == "sentence_transformers" else ""
    dim = settings.EMBEDDING_DIM
    ingested_ids = list(
        Document.objects.filter(chunks__isnull=False).values_list("id", flat=True).distinct()
    )
    Document.objects.filter(id__in=ingested_ids).update(
        embedding_backend=backend, embedding_model=model, embedding_dim=dim
    )


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_document_document_tier_1_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='embedding_backend',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='embedding_dim',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='embedding_model',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.RunPython(backfill_embedding_provenance, migrations.RunPython.noop),
    ]
