# Generated by Django 5.2.15 on 2026-07-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('corpus', '0003_document_embedding_backend_document_embedding_dim_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='document',
            name='document_tier_1_only',
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('tier__in', [1, 2])), name='document_enabled_tiers_only'),
        ),
    ]
