# Generated by Django 5.2.15 on 2026-07-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0004_widen_tier_guard_to_tier_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='tier',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Tier 1 — policies, handbooks, schedules (no student data)'), (2, 'Tier 2 — curriculum & lesson plans'), (3, 'Tier 3 — student records (not enabled)')], default=1),
        ),
    ]
