# Generated by Django 5.2.15 on 2026-07-03 23:45

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0005_alter_document_tier2_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('curriculum_map', 'Curriculum map'), ('scope_and_sequence', 'Scope & sequence'), ('pacing_guide', 'Pacing guide'), ('unit_plan', 'Unit plan'), ('lesson_plan', 'Lesson plan')], max_length=32), blank=True, default=list, help_text='Multi-valued: districts collapse map+pacing+S&S into one file.', size=None)),
                ('merged_artifact', models.BooleanField(default=False, help_text='True when one file genuinely IS several artifact types.')),
                ('grades', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=8), blank=True, default=list, help_text='Instructional grade(s), e.g. ["K", "1", "2"].', size=None)),
                ('subject', models.CharField(blank=True, choices=[('ela', 'English Language Arts'), ('math', 'Mathematics'), ('science', 'Science'), ('social_studies', 'Social Studies')], max_length=32)),
                ('document_mode', models.CharField(blank=True, choices=[('prescribed_planned', 'Prescribed / planned'), ('enacted_actual', 'Enacted / actual')], max_length=32)),
                ('lifecycle_status', models.CharField(blank=True, choices=[('living', 'Living (continuously revised)'), ('point_in_time', 'Point-in-time')], max_length=32)),
                ('revision_date', models.DateField(blank=True, null=True)),
                ('field_provenance', models.JSONField(blank=True, default=dict, help_text='Per-field {source, confidence}; supports coordinator override.')),
                ('authorship_level', models.CharField(blank=True, choices=[('district_consensus', 'District consensus'), ('school', 'School'), ('individual_teacher', 'Individual teacher')], help_text='The access-decision key: consensus docs are staff-visible; teacher-authored plans are section-scoped.', max_length=32)),
                ('school_year', models.CharField(blank=True, help_text='e.g. "2025-26". MUST be sourced from the SIS/coordinator, never from file timestamps (plans are copied year to year).', max_length=9)),
                ('sis_teacher_id', models.CharField(blank=True, max_length=128)),
                ('sis_section_id', models.CharField(blank=True, max_length=128)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='corpus.document')),
                ('parent_document', models.ForeignKey(blank=True, help_text="Hierarchy: a lesson's unit, a unit's map.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_curriculum_docs', to='corpus.document')),
            ],
        ),
    ]
