# Generated by Django 5.2.15 on 2026-07-03 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('chat', 'Chat exchange')], default='chat', max_length=20)),
                ('username', models.CharField(max_length=150)),
                ('role_slug', models.CharField(blank=True, max_length=50)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('retrieved', models.JSONField(default=list, help_text='Every chunk shown to the model: document, rank, distance, and the exact passage text.')),
                ('refused', models.BooleanField(default=False, help_text='True when retrieval was too thin to answer.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.conversation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit log entry',
                'verbose_name_plural': 'audit log',
                'ordering': ['-created_at'],
            },
        ),
    ]
