# Generated by Django 5.2.15 on 2026-07-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='error',
            field=models.TextField(blank=True, help_text='Set when the answer engine could not be reached or failed; the user got a friendly notice instead of an answer. Blank on normal exchanges.'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='refused',
            field=models.BooleanField(default=False, help_text='True when no grounded answer was delivered — retrieval was too thin, or the answer engine failed (see error).'),
        ),
    ]
